name: sqlite3_ffi
version: 0.0.1
description: >-
  Sqlite3 wrapper for dart:ffi.
author: Daco Harkes <dacoharkes@google.com>, Samir Jindel <sjindel@google.com>
environment:
  sdk: '>=2.1.0 <3.0.0'
dev_dependencies:
  test: ^1.5.3